CREATE TABLE IF NOT EXISTS "school_timetable" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" varchar NOT NULL,
    "days_weekly" int NOT NULL,
    "begin_date" datetime NOT NULL,
    "end_date" datetime NOT NULL,
    "begin_time" datetime NOT NULL,
    "end_time" datetime NOT NULL,
    "class_id" bigint NOT NULL,
    "teacher_id" bigint NOT NULL,
    "classroom_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '课程表';

CREATE TABLE IF NOT EXISTS "school_subject" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "remark" varchar NOT NULL,
    "class_hour" int,
    "is_show" varchar NOT NULL,
    "campus_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '科目表';

CREATE TABLE IF NOT EXISTS "school_teacher" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "user_id" bigint NOT NULL,
    "campus_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '教室表';

CREATE TABLE IF NOT EXISTS "school_campus" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "campus_type" varchar NOT NULL,
    "phone" varchar NOT NULL,
    "brand_name" varchar NOT NULL,
    "logourl" varchar NOT NULL,
    "slogan" varchar NOT NULL,
    "introduction" varchar NOT NULL,
    "location" varchar NOT NULL,
    "found_date" datetime NOT NULL,
    "tenant_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '校区表';

CREATE TABLE IF NOT EXISTS "school_class_student" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "number" bigint NOT NULL,
    "class_hour" int,
    "total_class_hour" int,
    "enter_date" datetime NOT NULL,
    "class_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '班级学生表';

CREATE TABLE IF NOT EXISTS "school_classroom" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "campus_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '教室表';

CREATE TABLE IF NOT EXISTS "school_class" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "max_students" int NOT NULL,
    "status" varchar NOT NULL,
    "plan_open_date" datetime,
    "open_date" datetime,
    "remark" varchar NOT NULL,
    "course_id" bigint NOT NULL,
    "head_teacher_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '班级表';

CREATE TABLE IF NOT EXISTS "school_course" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "introduction" varchar NOT NULL,
    "teaching_mode" varchar NOT NULL,
    "subject_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '课程表';

CREATE TABLE IF NOT EXISTS "school_course_fee" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" varchar NOT NULL,
    "class_hour" int,
    "total_price" int,
    "remark" varchar NOT NULL,
    "status" varchar NOT NULL,
    "course_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '课程收费表';

CREATE TABLE IF NOT EXISTS "school_holiday" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "begin_date" datetime NOT NULL,
    "end_date" datetime NOT NULL,
    "campus_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '假期表';

CREATE TABLE IF NOT EXISTS "school_student" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "birthday" datetime,
    "contact_name" varchar NOT NULL,
    "contact_relationship" varchar NOT NULL,
    "contact_phone" varchar NOT NULL,
    "attendance_date" datetime NOT NULL,
    "status" varchar NOT NULL,
    "expire_date" datetime NOT NULL,
    "campus_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '学生表';